services:
  node-server:
    image: mingfunwong/fibos
    volumes:
      - ./fibos-node/data:/node/data
    ports:
      - "8080:8870"
      - "9870:9870"
    env_file:
      - ./.env
    restart: unless-stopped
    stop_grace_period: 1m
