apiVersion: v1
kind: Service
metadata:
  name: fibos-node-1-service
  labels:
    app: fibos-node-1
spec:
  type: NodePort
  ports:
    - name: '8080'
      port: 8080
      targetPort: 8080
    - name: '30977'
      port: 30977
      targetPort: 9977
      nodePort: 30977
  selector:
    app: fibos-node-1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fibos-node-1-config
data:
  PRODUCER_ENABLE: 'false'
  PRODUCER_NAME: ''
  PUBLIC_KEY: ''
  PRIVATE_KEY: ''
  PRODUCER_API_ENABLE: 'false'
  SNAPSHOT_ENABLE: 'true'
  SNAPSHOT_URL: https://github.com/andy-backup/fibos/raw/master/snapshot.bin
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fibos-node-1-ingress
spec:
  rules:
    - host:
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: fibos-node-1-service
                port:
                  number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fibos-node-1
  labels:
    app: fibos-node-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibos-node-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fibos-node-1
    spec:
      containers:
        - image: mingfunwong/fibos:v1.7.1.12
          name: fibos
          resources: {}
          env:
            - name: PRODUCER_ENABLE
              valueFrom:
                configMapKeyRef:
                  name: fibos-node-1-config
                  key: PRODUCER_ENABLE
            - name: PRODUCER_NAME
              valueFrom:
                configMapKeyRef:
                  name: fibos-node-1-config
                  key: PRODUCER_NAME
            - name: PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: fibos-node-1-config
                  key: PUBLIC_KEY
            - name: PRIVATE_KEY
              valueFrom:
                configMapKeyRef:
                  name: fibos-node-1-config
                  key: PRIVATE_KEY
            - name: PRODUCER_API_ENABLE
              valueFrom:
                configMapKeyRef:
                  name: fibos-node-1-config
                  key: PRODUCER_API_ENABLE
            - name: SNAPSHOT_ENABLE
              valueFrom:
                configMapKeyRef:
                  name: fibos-node-1-config
                  key: SNAPSHOT_ENABLE
            - name: SNAPSHOT_URL
              valueFrom:
                configMapKeyRef:
                  name: fibos-node-1-config
                  key: SNAPSHOT_URL
